// Auth
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Editor
export const CLEAR_EDITOR_DATA = 'CLEAR_EDITOR_DATA';
export const SET_QUESTION_DATA = 'SET_QUESTION_DATA';
export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';
export const UPDATE_CURRENT_CODE = 'UPDATE_CURRENT_CODE';
export const UPDATE_EDITOR_MENU_SELECTION = 'UPDATE_EDITOR_MENU_SELECTION';

// Output
export const SET_OUTPUT_VALUE = 'SET_OUTPUT_VALUE';
export const CLEAR_OUTPUT_VALUE = 'CLEAR_OUTPUT_VALUE';
export const SET_OUTPUT_LOADING_STATUS = 'SET_OUTPUT_LOADING_STATUS';
export const SET_OUTPUT_ERRORS = 'SET_OUTPUT_ERRORS';
export const CLEAR_OUTPUT_ERRORS = 'CLEAR_OUTPUT_ERRORS';
